# -*- coding: utf-8 -*-
"""practica 14 Ehrenfest.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BM1xAwTbZJeDw6NKjvnuuedMdFeMnbl8
"""

import numpy as np
import matplotlib.pyplot as plt
def UrnaT(n,i, t):
  A=i
  turnos=0
  estados=[]
  estados.append(A)
  for i in range(0,t):
    turnos+=1
    A+=np.random.choice([-1,1],1, p=[A/n, (n-A)/n])[0]
    estados.append(A)
    t=np.arange(0,turnos+1)
  return([t,estados])


def UrnaEstado(n,s, i):  
  A=i
  turnos=0
  estados=[]
  estados.append(A)
  while(A!=s):
    turnos+=1
    A+=np.random.choice([-1,1],1, p=[A/n, (n-A)/n])[0]
    estados.append(A)
  t=np.arange(0,turnos+1)
  return([t,estados])

n=40
i=40
s=20
t=80
resultados=UrnaEstado(n,s,i)
plt.plot(resultados[0], resultados[1])

#resultados=UrnaT(n,i,t)
#plt.plot(resultados[0], resultados[1])
plt.xlabel('Tiempo')
plt.ylabel('Partículas en la urna A')
print('El tiempo que se tardó en llegar a ',s, 'fue de ',resultados[0][-1])

import seaborn as sns

def UrnaTurnos(n,s, i):  
  A=i
  turnos=0
  while(A!=s):
    turnos+=1
    A+=np.random.choice([-1,1],1, p=[A/n, (n-A)/n])[0]
  return(turnos)


#UrnaTurnos(1000, 700,1000)

v=1000
vect=[]
for i in range(1,v):
  vect.append(UrnaT(100, 0, 50)[1][-1])

res=np.sum(vect)/v
print(res)

sns.set_style('darkgrid')
sns.distplot(vect)
print(vect[0])

def UrnaEstado(n,s, i):  
  A=i
  turnos=0
  estados=[]
  estados.append(A)
  while(A!=s):
    turnos+=1
    A+=np.random.choice([-1,1],1, p=[A/n, (n-A)/n])[0]
    estados.append(A)
  t=np.arange(0,turnos+1)
  return(turnos)

v=1000
vec=[]
for i in range(1,v):
  vec.append(UrnaEstado(100,50,00))

r=np.sum(vec)/len(vec)
print(r)
 

sns.set_style('darkgrid')
sns.distplot(vec)
print(vect[0])